# pyright: reportMissingTypeStubs=false
"""
Excel export — exact replica of original Balance.xlsx style, populated from live DB.
Every font, border, number format, column width, row height, merge, and freeze pane
is matched to the original file as inspected cell-by-cell.
"""

from core.reports.excel_formatting_helpers import (
    FMT_EGP,
    FMT_EGP_RED,
    FMT_USD,
    FMT_EUR,
    FMT_SAR,
    FMT_GOLD,
    FMT_EGP_CERT,
    FMT_EGP_CERT_R,
    FMT_PCT,
    FMT_DATE,
    FMT_INT,
    GREY,
    RED,
    WHITE,
    EXP_BG,
    EXP_MONTH_BG,
    EXP_YEAR_BG,
    MONTH_ORDER,
    auto_adjust_columns,
    _f,
    _thin,
    _thin_lr,
    _thin_tb,
    _thin_b,
    _thin_t,
    _fill,
    _align,
    _center,
    _msort,
    _apply_zebra_striping,
)
from core.reports.excel_salary_builder import (
    SALARY_COL_WIDTHS,
    YEAR_ROW_HT,
    SALARY_FREEZE,
    _apply_data_row,
    _apply_total_row,
    build_salary_sheet,
)
from core.reports.excel_sheets_builder import (
    CURRENCIES,
    build_exchange_rates_sheet,
    build_gold_price_sheet,
    build_bank_certificates_sheet,
    build_balance_sheet,
    build_expenses_sheet,
)
from core.reports.excel_main_generator import generate_excel

__all__ = [
    "FMT_EGP",
    "FMT_EGP_RED",
    "FMT_USD",
    "FMT_EUR",
    "FMT_SAR",
    "FMT_GOLD",
    "FMT_EGP_CERT",
    "FMT_EGP_CERT_R",
    "FMT_PCT",
    "FMT_DATE",
    "FMT_INT",
    "GREY",
    "RED",
    "WHITE",
    "EXP_BG",
    "EXP_MONTH_BG",
    "EXP_YEAR_BG",
    "MONTH_ORDER",
    "SALARY_COL_WIDTHS",
    "YEAR_ROW_HT",
    "SALARY_FREEZE",
    "CURRENCIES",
    "auto_adjust_columns",
    "_f",
    "_thin",
    "_thin_lr",
    "_thin_tb",
    "_thin_b",
    "_thin_t",
    "_fill",
    "_align",
    "_center",
    "_msort",
    "_apply_zebra_striping",
    "_apply_data_row",
    "_apply_total_row",
    "build_salary_sheet",
    "build_exchange_rates_sheet",
    "build_gold_price_sheet",
    "build_bank_certificates_sheet",
    "build_balance_sheet",
    "build_expenses_sheet",
    "generate_excel",
]