"""Umbrella re-export for the remaining Settings-page views that aren't
already covered by exports_auth.py (User/Permission mgmt) or
exports_financial_core.py (Company/Bank): app settings, email
templates, AI connection settings, property-rate scraping, gold &
market rates, currency, backup/restore, reminders, certificate status,
translations, and the documentation capture engine.

Whenever core/views/settings/ adds/removes a public name in one of
these areas, update the imports/__all__ below to match — this file is
what core/views/__init__.py depends on, so no other file needs to
change when settings/ is reorganized internally.
"""

from .settings import (
    SettingsView,
    EmailTemplateListView,
    EmailTemplateDetailView,
    EmailSettingsTestView,
    AISettingsView,
    AIConnectionTestView,
    AIProviderListView,
    ScrapePropertyRatesView,
    GoldTypeSettingsListView,
    GoldTypeSettingsDetailView,
    GoldPuritySettingsListView,
    GoldPuritySettingsDetailView,
    ExchangeRateListView,
    ExchangeRateRefreshView,
    GoldPriceListView,
    GoldPriceRefreshView,
    CurrencyListView,
    CurrencyDetailView,
    _seed_gold_settings_defaults,
    BackupCreateView,
    BackupListView,
    BackupDeleteView,
    BackupRestoreView,
    ReminderRuleListView,
    ReminderRuleDetailView,
    ReminderCheckView,
    ReminderLogListView,
    CertificateStatusListView,
    CertificateStatusDetailView,
    get_translations,
    save_translations,
    scan_translations,
    DocumentationStatusView,
    DocumentationDevicesView,
    DocumentationHistoryView,
    ValidateCaptureView,
    ValidateGenerationView,
    CaptureScreenshotsView,
    GenerateDocumentsView,
    CancelDocumentationView,
    OpenFolderView,
)

__all__ = [
    "SettingsView",
    "EmailTemplateListView",
    "EmailTemplateDetailView",
    "EmailSettingsTestView",
    "AISettingsView",
    "AIConnectionTestView",
    "AIProviderListView",
    "ScrapePropertyRatesView",
    "GoldTypeSettingsListView",
    "GoldTypeSettingsDetailView",
    "GoldPuritySettingsListView",
    "GoldPuritySettingsDetailView",
    "ExchangeRateListView",
    "ExchangeRateRefreshView",
    "GoldPriceListView",
    "GoldPriceRefreshView",
    "CurrencyListView",
    "CurrencyDetailView",
    "_seed_gold_settings_defaults",
    "BackupCreateView",
    "BackupListView",
    "BackupDeleteView",
    "BackupRestoreView",
    "ReminderRuleListView",
    "ReminderRuleDetailView",
    "ReminderCheckView",
    "ReminderLogListView",
    "CertificateStatusListView",
    "CertificateStatusDetailView",
    "get_translations",
    "save_translations",
    "scan_translations",
    "DocumentationStatusView",
    "DocumentationDevicesView",
    "DocumentationHistoryView",
    "ValidateCaptureView",
    "ValidateGenerationView",
    "CaptureScreenshotsView",
    "GenerateDocumentsView",
    "CancelDocumentationView",
    "OpenFolderView",
]
