# Generated by Django 6.0.5 on 2026-05-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(blank=True, max_length=100)),
                ('buy_rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('sell_rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('mid_rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('source', models.CharField(default='open.er-api.com', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at', 'currency_code'],
            },
        ),
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat_24k', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carat_22k', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carat_21k', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carat_18k', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usd_gram_24k', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('usd_per_oz', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('usd_to_egp', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('source_gold', models.CharField(default='api.gold-api.com', max_length=100)),
                ('source_fx', models.CharField(default='open.er-api.com', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
