# Generated by Django 6.0.5 on 2026-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exchangerate_goldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldprice',
            name='carat_18k_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='carat_21k_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='carat_22k_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='carat_24k_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
