# Generated by Django 6.0.6 on 2026-06-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assetphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetphoto',
            name='image',
        ),
        migrations.AlterField(
            model_name='assetphoto',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
