# Generated by Django 6.0.6 on 2026-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_assetphoto_image_alter_assetphoto_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetphoto',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assetphoto',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetphoto',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
