# Generated by Django 6.0.6 on 2026-09-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plan_prices_currency_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
