# Generated by Django 4.2.30 on 2026-05-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appsettings_id_alter_balanceentry_id_and_more'),
    ]

    operations = [
    ]
