# Generated by Django 6.0.6 on 2026-07-02 07:38

import django.db.models.deletion
from django.db import migrations, models


def map_legacy_asset_types(apps, schema_editor):
    FixedAsset = apps.get_model('core', 'FixedAsset')
    real_estate_types = ['Apartment', 'Villa', 'Land', 'Shop', 'Office']

    FixedAsset.objects.filter(asset_type__in=real_estate_types).update(asset_type='Real Estate')
    FixedAsset.objects.filter(asset_type='Car').update(asset_type='Vehicles')
    FixedAsset.objects.filter(asset_type='Other').update(asset_type='Other Assets')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assetmortgage_assetrental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_type',
            field=models.CharField(choices=[('Real Estate', 'Real Estate'), ('Vehicles', 'Vehicles'), ('Gold', 'Gold'), ('Other Assets', 'Other Assets')], max_length=30),
        ),
        migrations.RunPython(map_legacy_asset_types, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AssetInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='core.fixedasset')),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maintenance_type', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='core.fixedasset')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoldDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_type', models.CharField(blank=True, max_length=100)),
                ('purity', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('unit', models.CharField(default='gram', max_length=20)),
                ('market_price', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('purchase_weight', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_details', to='core.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='OtherAssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_asset_details', to='core.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=100)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('mileage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plate_number', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='core.fixedasset')),
            ],
        ),
    ]
