# Generated by Django 6.0.6 on 2026-09-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_upgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allows_ai_workspace',
            field=models.BooleanField(default=False),
        ),
    ]
