# Generated by Django 6.0.5 on 2026-05-31 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appsettings_id_alter_balanceentry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcertificate',
            name='frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bankcertificate',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bankcertificate',
            name='interest_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankcertificate',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='core.bank'),
        ),
    ]
