# Generated by Django 6.0.5 on 2026-05-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bankcertificate_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcertificate',
            name='certificate_number',
        ),
    ]
