# Generated by Django 4.2.30 on 2026-06-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_bankcertificate_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceentry',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
