# Generated by Django 6.0.6 on 2026-07-04 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_backfill_closed_certificate_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_object_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('document_category', models.CharField(max_length=100)),
                ('original_file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('file_content', models.BinaryField()),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date', '-id'],
                'indexes': [models.Index(fields=['parent_object_type', 'content_type', 'object_id'], name='core_docume_parent__536b48_idx')],
            },
        ),
    ]
