# Generated by Django 6.0.6 on 2026-09-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_sysadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='appsettings',
            unique_together={('key', 'owner')},
        ),
    ]
