# Generated by Django 6.0.6 on 2026-07-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bankcertificate_options_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatedetails',
            name='last_estimated_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='last_valuation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='valuation_provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='rule_type',
            field=models.CharField(choices=[('cert_maturity', 'Certificate Maturity'), ('insurance_expiry', 'Insurance Expiry'), ('vehicle_license_expiry', 'Vehicle License Expiry'), ('property_tax_reminder', 'Property Tax Reminder'), ('salary_unpaid', 'Salary Unpaid'), ('salary_day', 'Salary Day'), ('custom', 'Custom')], default='cert_maturity', max_length=50),
        ),
    ]
