# Generated by Django 6.0.6 on 2026-09-18 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_per_user_app_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatestatus',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goldpuritysetting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_purities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goldtypesetting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificatestatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='goldpuritysetting',
            name='key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='goldtypesetting',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='certificatestatus',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('owner', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='goldpuritysetting',
            unique_together={('owner', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='goldtypesetting',
            unique_together={('owner', 'name')},
        ),
    ]
