# Generated by Django 4.2.30 on 2026-06-05 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_expensecategory_expensesubcategory_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('companies', 'Companies'), ('salary', 'Salary'), ('banks', 'Banks'), ('bank_certificates', 'Bank Certificates'), ('currencies', 'Currencies'), ('balance', 'Balance'), ('settings', 'Settings'), ('expense-categories', 'Expense Categories'), ('exchange_rates', 'Exchange Rates'), ('gold_price', 'Gold Price'), ('user_management', 'User Management'), ('expenses', 'Expenses'), ('reports', 'Reports')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
