# Generated by Django 4.2.30 on 2026-06-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_pagepermission_page_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_b64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
