# Generated by Django 6.0.6 on 2026-06-15 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_userprofile_avatar_userprofile_avatar_b64'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color_hex', models.CharField(default='#1a6ef5', max_length=7)),
                ('is_default', models.BooleanField(default=False, help_text='Used as default status for new certs')),
                ('is_terminal', models.BooleanField(default=False, help_text='No further renewals expected')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('cert_maturity', 'Certificate Maturity'), ('salary_unpaid', 'Salary Unpaid'), ('salary_day', 'Salary Day'), ('custom', 'Custom')], default='cert_maturity', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('days_before', models.IntegerField(default=30, help_text='Days before expiry (cert_maturity)')),
                ('salary_trigger', models.CharField(blank=True, choices=[('day_of_month', 'Day of Month'), ('days_before_eom', 'Days Before End of Month'), ('days_after_som', 'Days After Start of Month')], default='day_of_month', max_length=50)),
                ('salary_day', models.IntegerField(default=25, help_text='Trigger value for salary reminder')),
                ('salary_message', models.CharField(blank=True, default='Salary reminder: check if this month has been paid', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('fired_on', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.reminderrule')),
            ],
            options={
                'ordering': ['-fired_on'],
                'unique_together': {('rule', 'related_model', 'related_id', 'fired_on')},
            },
        ),
    ]
