# Generated by Django 6.0.6 on 2026-06-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reminder_engine_cert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceentry',
            name='balance_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('certificate', 'Certificate'), ('investment', 'Investment')], default='cash', max_length=20),
        ),
    ]
