# Generated by Django 6.0.6 on 2026-07-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assetpurchasepayment_assetsale_deposit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('companies', 'Companies'), ('salary', 'Salary'), ('all_companies', 'All Companies'), ('banks', 'Banks'), ('bank_certificates', 'Bank Certificates'), ('currencies', 'Currencies'), ('balance', 'Balance'), ('settings', 'Settings'), ('expense-categories', 'Expense Categories'), ('exchange_rates', 'Exchange Rates'), ('gold_price', 'Gold Price'), ('user_management', 'User Management'), ('expenses', 'Expenses'), ('reports', 'Reports'), ('fixed_assets', 'Fixed Assets'), ('advanced_reports', 'Advanced Reports'), ('financial_advisor', 'Financial Advisor')], max_length=50),
        ),
    ]
