# Generated by Django 6.0.6 on 2026-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
