# Generated by Django 6.0.6 on 2026-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_balanceentry_balance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('carat_24k', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carat_21k', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carat_18k', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usd_gram_24k', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('usd_per_oz', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
