# Generated by Django 6.0.6 on 2026-06-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_goldpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpricehistory',
            name='usd_to_egp',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
