# Generated by Django 6.0.6 on 2026-06-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_goldpricehistory_usd_to_egp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricehistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
