# Generated by Django 6.0.6 on 2026-06-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_goldpricehistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
