# Generated by Django 6.0.6 on 2026-06-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_goldpricehistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceentry',
            name='balance_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('certificate', 'Certificate'), ('gold', 'Gold')], default='cash', max_length=20),
        ),
    ]
