# Generated by Django 6.0.6 on 2026-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_balanceentry_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceentry',
            name='balance_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('gold', 'Gold'), ('certificate', 'Certificate')], default='cash', max_length=20),
        ),
    ]
