# Generated by Django 6.0.6 on 2026-07-13 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_balancetransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAcquisitionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount_egp', models.DecimalField(decimal_places=2, max_digits=16)),
                ('usd_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_costs', to='core.fixedasset')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
