# Generated by Django 6.0.6 on 2026-06-26 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_balanceentry_balance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Land', 'Land'), ('Shop', 'Shop'), ('Office', 'Office'), ('Car', 'Car'), ('Other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('Owned', 'Owned'), ('Sold', 'Sold')], default='Owned', max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('purchase_usd_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('purchase_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('current_market_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valuation_source', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20)),
                ('last_valuation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetValuationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valuation_source', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_history', to='core.fixedasset')),
            ],
            options={
                'ordering': ['-valuation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('selling_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_sale_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_sales', to='core.balanceentry')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='core.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetRenovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount_egp', models.DecimalField(decimal_places=2, max_digits=16)),
                ('usd_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovations', to='core.fixedasset')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssetFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('amount_egp', models.DecimalField(decimal_places=2, max_digits=16)),
                ('usd_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='core.fixedasset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Egypt', max_length=100)),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('full_address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('floor_number', models.PositiveSmallIntegerField(default=0)),
                ('building_floors', models.PositiveSmallIntegerField(default=0)),
                ('build_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_gas', models.BooleanField(default=False)),
                ('electricity_meter_private', models.BooleanField(default=True)),
                ('water_meter_private', models.BooleanField(default=False)),
                ('has_land_share', models.BooleanField(default=False)),
                ('land_share_ratio', models.CharField(blank=True, max_length=50)),
                ('facing', models.CharField(blank=True, max_length=100)),
                ('finishing_level', models.CharField(blank=True, max_length=100)),
                ('furnished_status', models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi Furnished', 'Semi Furnished'), ('Fully Furnished', 'Fully Furnished')], default='Unfurnished', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate', to='core.fixedasset')),
            ],
        ),
    ]
