# Generated by Django 6.0.6 on 2026-10-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_grant_budgets_import_to_member_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldprice',
            options={'ordering': ['-fetched_at', '-id']},
        ),
    ]
