# Generated by Django 6.0.6 on 2026-07-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_assetacquisitioncost'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_egp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14),
        ),
    ]
