# Generated by Django 6.0.6 on 2026-06-27 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_realestatedetails_area_m2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestatedetails',
            old_name='electricity',
            new_name='electricity_meter_private',
        ),
        migrations.RenameField(
            model_name='realestatedetails',
            old_name='address',
            new_name='full_address',
        ),
        migrations.RenameField(
            model_name='realestatedetails',
            old_name='elevator',
            new_name='has_elevator',
        ),
        migrations.RenameField(
            model_name='realestatedetails',
            old_name='garage',
            new_name='has_garage',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='apartment_area',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='building_year',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='facades',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='land_share',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='realestatedetails',
            name='water',
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='area_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='build_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='facing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='furnished_status',
            field=models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi Furnished', 'Semi Furnished'), ('Fully Furnished', 'Fully Furnished')], default='Unfurnished', max_length=50),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='has_gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='has_land_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='land_share_ratio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='land_share_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='realestatedetails',
            name='water_meter_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='building_floors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='country',
            field=models.CharField(default='Egypt', max_length=100),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='floor_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='licensed',
            field=models.BooleanField(default=False),
        ),
    ]
