# Generated by Django 6.0.6 on 2026-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_documentationexecution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentationexecution',
            name='duration',
        ),
        migrations.AlterField(
            model_name='documentationexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
