# Generated by Django 6.0.6 on 2026-07-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_documentationexecution_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationexecution',
            name='execution_type',
            field=models.CharField(choices=[('CAPTURE', 'Capture'), ('GENERATION', 'Generation'), ('BOTH', 'Capture & Generate')], default='BOTH', max_length=20),
        ),
        migrations.AddField(
            model_name='documentationexecution',
            name='files_generated',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
