# Generated by Django 6.0.6 on 2026-07-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_documentationexecution_execution_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationexecution',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentationexecution',
            name='missing_content_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentationexecution',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentationexecution',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
