# Generated by Django 6.0.6 on 2026-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_billing_admin_suspend_void_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_before_deletion',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
