# Generated by Django 6.0.6 on 2026-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_documentationexecution_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationexecution',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentationexecution',
            name='engine_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentationexecution',
            name='git_commit_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
