# Generated by Django 6.0.6 on 2026-07-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_documentationexecution_app_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(blank=True, max_length=100)),
                ('buy_rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('sell_rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('mid_rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('source', models.CharField(default='open.er-api.com', max_length=100)),
                ('fetched_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_date', models.DateField()),
            ],
            options={
                'ordering': ['-snapshot_date', 'currency_code'],
                'indexes': [models.Index(fields=['currency_code', 'snapshot_date'], name='core_exchan_currenc_e8de4d_idx')],
                'unique_together': {('currency_code', 'snapshot_date')},
            },
        ),
    ]
