# Generated by Django 6.0.6 on 2026-10-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userprofile_deletion_requested_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-fetched_at', 'currency_code', '-id']},
        ),
    ]
