# Generated by Django 6.0.6 on 2026-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_exchangeratehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('financial_advisor', 'Financial Advisor'), ('employment', 'Employment'), ('balance', 'Balance'), ('bank_certificates', 'Bank Certificates'), ('fixed_assets', 'Fixed Assets'), ('exchange_rates', 'Exchange Rates'), ('gold_price', 'Gold Price'), ('expenses', 'Expenses'), ('expense-categories', 'Expense Categories'), ('reports', 'Reports'), ('advanced_reports', 'Advanced Reports'), ('settings', 'Settings'), ('user_management', 'User Management')], max_length=50),
        ),
    ]
