# Generated by Django 6.0.6 on 2026-08-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_pagepermission_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_baseline_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('house', 'Buy House'), ('car', 'Buy Car'), ('salary_change', 'Salary Change'), ('marriage', 'Marriage'), ('child', 'Child'), ('retirement', 'Retirement'), ('inheritance', 'Inheritance'), ('medical', 'Medical Event'), ('business', 'Start Business'), ('job_loss', 'Job Loss')], max_length=50)),
                ('event_date', models.DateField()),
                ('params', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.scenario')),
            ],
            options={
                'ordering': ['order', 'event_date', 'id'],
            },
        ),
    ]
