# Generated by Django 6.0.6 on 2026-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_aiconversation_aimessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
