# Generated by Django 6.0.6 on 2026-08-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_aimessage_tool_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='completion_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
