# Generated by Django 6.0.6 on 2026-08-05 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_aimessage_completion_tokens_aimessage_prompt_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_date', models.DateField()),
                ('from_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('to_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed'), ('EDITED', 'Edited')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_out', to='core.balanceentry')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_from', to='core.currency')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_currency_exchanges', to=settings.AUTH_USER_MODEL)),
                ('to_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_in', to='core.balanceentry')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_to', to='core.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exchange_date', '-id'],
            },
        ),
    ]
