# Generated by Django 6.0.6 on 2026-08-06 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_currencyexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('business_rule', 'Business Rule & Calculation'), ('codebase_architecture', 'Codebase Architecture & Services'), ('user_preference', 'User Directive & Preference'), ('app_evolution', 'Application Evolution & Feature')], default='business_rule', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(default='autonomous_learning', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('base_model', models.CharField(default='llama3:latest', max_length=100)),
                ('training_backend', models.CharField(default='ollama', max_length=50)),
                ('dataset_version', models.CharField(default='v1.0', max_length=50)),
                ('benchmark_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('metadata_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIBenchmarkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_analysis_score', models.FloatField(default=0.0)),
                ('financial_reasoning_score', models.FloatField(default=0.0)),
                ('architecture_score', models.FloatField(default=0.0)),
                ('code_understanding_score', models.FloatField(default=0.0)),
                ('feature_suggestion_score', models.FloatField(default=0.0)),
                ('hallucination_resistance_score', models.FloatField(default=0.0)),
                ('instruction_following_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('passed_promotion_gate', models.BooleanField(default=False)),
                ('evaluation_details_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='core.aimodelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
