# Generated by Django 6.0.6 on 2026-08-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_acquisition_furniture_rental_balance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_type',
            field=models.CharField(blank=True, choices=[('asset_renovation', 'Asset Renovation'), ('asset_acquisition_cost', 'Asset Acquisition Cost'), ('asset_furniture', 'Asset Furniture')], default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type__gt', '')), fields=('source_type', 'source_id'), name='unique_expense_mirror_source'),
        ),
    ]
