# Generated by Django 6.0.6 on 2026-08-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_expense_source_mirror_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrenovation',
            options={'ordering': ['-date', '-id']},
        ),
    ]
