# Generated by Django 6.0.6 on 2026-08-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_assetrenovation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetacquisitioncost',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='assetfurniture',
            options={'ordering': ['-purchase_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='assetinsurance',
            options={'ordering': ['-expiry_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='assetmaintenance',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='assetphoto',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
