# Generated by Django 6.0.6 on 2026-08-31 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_bankinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source_type',
            field=models.CharField(blank=True, choices=[('asset_renovation', 'Asset Renovation'), ('asset_acquisition_cost', 'Asset Acquisition Cost'), ('asset_furniture', 'Asset Furniture'), ('credit_card_payment', 'Credit Card Payment')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Bank Transfer', 'Bank Transfer')], default='Card', max_length=20)),
                ('card_label', models.CharField(blank=True, help_text="Free-text identifier for the untracked credit card, e.g. 'Visa ****1234'.", max_length=100)),
                ('amount_egp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bank')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
