# Generated by Django 6.0.6 on 2026-09-01 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_creditcardpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source_type',
            field=models.CharField(blank=True, choices=[('asset_renovation', 'Asset Renovation'), ('asset_acquisition_cost', 'Asset Acquisition Cost'), ('asset_furniture', 'Asset Furniture'), ('credit_card_payment', 'Credit Card Payment'), ('card_renewal_fee', 'Card Renewal Fee')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='CardRenewalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_date', models.DateField()),
                ('card_label', models.CharField(blank=True, help_text="Free-text identifier for the renewed card, e.g. 'Visa Debit ****1234'.", max_length=100)),
                ('amount_egp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bank')),
            ],
            options={
                'ordering': ['-fee_date', '-id'],
            },
        ),
    ]
