# Generated by Django 6.0.6 on 2026-09-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_expense_source_type_cardrenewalfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelversion',
            name='base_model',
            field=models.CharField(default='qwen2.5:3b', max_length=100),
        ),
    ]
