from django.urls import path
from .. import views

urlpatterns = [
    path(
        "api/financial-advisor/cash-flow-forecast/",
        views.CashFlowForecastView.as_view(),
    ),
    path(
        "api/financial-advisor/wealth-growth-forecast/",
        views.WealthGrowthForecastView.as_view(),
    ),
    path(
        "api/financial-advisor/overview/",
        views.OverviewView.as_view(),
    ),
    path(
        "api/financial-advisor/portfolio-optimizer/",
        views.PortfolioOptimizerView.as_view(),
    ),
    path(
        "api/financial-advisor/risk-analysis/",
        views.RiskAnalysisView.as_view(),
    ),
    path(
        "api/financial-advisor/spending-intelligence/",
        views.SpendingIntelligenceView.as_view(),
    ),
    path(
        "api/financial-advisor/opportunity-detection/",
        views.OpportunityDetectionView.as_view(),
    ),
    path(
        "api/financial-advisor/performance/",
        views.PerformanceView.as_view(),
    ),
    path(
        "api/financial-advisor/what-if-simulator/",
        views.WhatIfSimulatorView.as_view(),
    ),
    path(
        "api/financial-advisor/scenario-planner/compare/",
        views.ScenarioComparisonView.as_view(),
    ),
    path(
        "api/scenarios/event-definitions/",
        views.ScenarioEventDefinitionsView.as_view(),
    ),
    path(
        "api/scenarios/",
        views.ScenarioListCreateView.as_view(),
    ),
    path(
        "api/scenarios/<int:pk>/",
        views.ScenarioDetailView.as_view(),
    ),
    path(
        "api/scenarios/<int:pk>/events/",
        views.ScenarioEventListCreateView.as_view(),
    ),
    path(
        "api/scenarios/<int:pk>/events/<int:event_id>/",
        views.ScenarioEventDetailView.as_view(),
    ),
    path(
        "api/scenarios/<int:pk>/duplicate/",
        views.ScenarioDuplicateView.as_view(),
    ),
    path(
        "api/financial-advisor/goal-planning/",
        views.GoalPlanningView.as_view(),
    ),
    path(
        "api/financial-advisor/ai/chat/",
        views.AIChatView.as_view(),
    ),
    path(
        "api/financial-advisor/ai/conversations/",
        views.AIConversationListView.as_view(),
    ),
    path(
        "api/financial-advisor/ai/conversations/<int:pk>/",
        views.AIConversationDetailView.as_view(),
    ),
    path(
        "api/financial-advisor/ai/progress/",
        views.AIProgressView.as_view(),
    ),
]
