from django.urls import path
from .. import views

urlpatterns = [
    path("api/rates/", views.ExchangeRateListView.as_view()),
    path("api/rates/refresh/", views.ExchangeRateRefreshView.as_view()),
    path("api/gold/", views.GoldPriceListView.as_view()),
    path("api/gold/refresh/", views.GoldPriceRefreshView.as_view()),
    path("", views.index),
    path("api/companies/", views.CompanyListView.as_view()),
    path("api/companies/<int:pk>/", views.CompanyDetailView.as_view()),
    path("api/salary/summary/", views.SalarySummaryView.as_view()),
    path("api/salary/generate-current/", views.GenerateCurrentSalaryView.as_view()),
    path("api/salary/", views.SalaryListView.as_view()),
    path("api/salary/<int:pk>/", views.SalaryDetailView.as_view()),
    path("api/salary/<int:pk>/mark-paid/", views.MarkSalaryPaidView.as_view()),
    path("api/per-diems/", views.PerDiemListView.as_view()),
    path("api/per-diems/<int:pk>/", views.PerDiemDetailView.as_view()),
    path("api/per-diems/currencies/", views.PerDiemCurrencyListView.as_view()),
    path("api/banks/", views.BankListView.as_view()),
    path("api/banks/with-balance/", views.BankWithBalanceListView.as_view()),
    path("api/banks/<int:pk>/", views.BankDetailView.as_view()),
    path("api/bank-certificates/", views.BankCertificateListView.as_view()),
    path("api/bank-certificates/<int:pk>/", views.BankCertificateDetailView.as_view()),
    path(
        "api/bank-certificates/<int:certificate_id>/interest-history/",
        views.BankCertificateInterestHistoryView.as_view(),
    ),
    path("api/currencies/", views.CurrencyListView.as_view()),
    path("api/currencies/<int:pk>/", views.CurrencyDetailView.as_view()),
    path("api/balance/", views.BalanceListView.as_view()),
    path("api/balance/<int:pk>/", views.BalanceDetailView.as_view()),
    path("api/balance-transfers/", views.BalanceTransferListView.as_view()),
    path("api/balance-transfers/<int:pk>/", views.BalanceTransferDetailView.as_view()),
    path("api/bank-interests/", views.BankInterestListView.as_view()),
    path("api/bank-interests/<int:pk>/", views.BankInterestDetailView.as_view()),
    path("api/credit-card-payments/", views.CreditCardPaymentListView.as_view()),
    path("api/credit-card-payments/<int:pk>/", views.CreditCardPaymentDetailView.as_view()),
    path("api/card-renewal-fees/", views.CardRenewalFeeListView.as_view()),
    path("api/card-renewal-fees/<int:pk>/", views.CardRenewalFeeDetailView.as_view()),
    path("api/currency-exchanges/", views.CurrencyExchangeListView.as_view()),
    path("api/currency-exchanges/<int:pk>/", views.CurrencyExchangeDetailView.as_view()),
    path("api/currency-exchanges/calculate/", views.CurrencyExchangeCalculateView.as_view()),
    path("api/currency-exchanges/options/", views.CurrencyExchangeFormOptionsView.as_view()),
    # Expenses
    path("api/expense-categories/", views.ExpenseCategoryListView.as_view()),
    path("api/expense-categories/<int:pk>/", views.ExpenseCategoryDetailView.as_view()),
    path("api/expense-subcategories/", views.ExpenseSubcategoryListView.as_view()),
    path(
        "api/expense-subcategories/<int:pk>/",
        views.ExpenseSubcategoryDetailView.as_view(),
    ),
    path("api/expenses/", views.ExpenseListView.as_view()),
    path("api/expenses/<int:pk>/", views.ExpenseDetailView.as_view()),
    path("api/expenses/summary/", views.ExpenseSummaryView.as_view()),
]
