"""
The ordered list of (prefix, model, natural_key_field) tuples that both
backup export and restore walk in sequence, to respect FK dependencies.
"""

from __future__ import annotations


def get_model_export_order():
    from axes.models import AccessAttempt, AccessAttemptExpiration, AccessFailureLog, AccessLog
    from django.contrib.admin.models import LogEntry
    from django.contrib.auth.models import Group, Permission, User
    from django.contrib.contenttypes.models import ContentType

    from core.models import (
        AIBenchmarkReport, AIConversation, AIKnowledgeEntry, AIMessage, AIModelVersion,
        AIAnswerFeedback, AIPrompt, AIPromptCategory,
        AppSettings, AssetAcquisitionCost, AssetFurniture, AssetInsurance,
        AssetMaintenance, AssetMortgage, AssetPhoto, AssetPurchasePayment,
        AssetRental, AssetRenovation, AssetSale, AssetValuationHistory,
        AuthAuditLog, AuthToken,
        Budget, RecurringTransaction,
        Bank, BankCertificate, BankCertificateInterestHistory, BankInterest,
        BalanceEntry, BalanceTransfer,
        CardRenewalFee, CertificateStatus, Company, CreditCardPayment,
        Currency, CurrencyExchange,
        Document, DocumentationExecution,
        EmailTemplate, Expense, ExpenseCategory, ExpenseSubcategory,
        ExchangeRate, ExchangeRateHistory,
        FixedAsset,
        Goal, GoldDetails, GoldPrice, GoldPriceHistory, GoldPuritySetting, GoldTypeSetting,
        OtherAssetDetails,
        PagePermission, PerDiem,
        Role, RolePermission, UserRole,
        RealEstateDetails, ReminderLog, ReminderRule,
        SalaryEntry, Scenario, ScenarioEvent,
        UserProfile,
        VehicleDetails,
        Plan, PlanPrice, Subscription, Invoice, UpgradeRequest,
    )

    return [
        # ContentType + Permission are restored by NATURAL KEY (app_label/model, codename), never by pk:
        # their ids differ between databases and a pk-preserving restore would corrupt every permission link.
        ("00", ContentType,                  None),
        ("01", Group,                        "name"),
        ("02", User,                         "username"),
        ("02b", Permission,                   None),
        # auth link tables (who belongs to which group / holds which permission): restored by natural key too.
        ("02c", Group.permissions.through,    None),
        ("02d", User.groups.through,          None),
        ("02e", User.user_permissions.through, None),
        ("03", Currency,                     "code"),
        ("04", Bank,                         None),
        ("05", Company,                      None),
        ("06", CertificateStatus,            "name"),
        ("07", GoldTypeSetting,              "name"),
        ("08", GoldPuritySetting,            "key"),
        ("09", AppSettings,                  "key"),
        ("10", EmailTemplate,                "key"),
        ("11", UserProfile,                  "user_id"),
        ("12", AuthToken,                    None),
        ("13", AuthAuditLog,                 None),
        ("14", PagePermission,               None),
        ("15", BalanceEntry,                 None),
        ("16", BalanceTransfer,              None),
        ("16b", CurrencyExchange,             None),
        ("17", ExchangeRate,                 None),
        ("18", SalaryEntry,                  None),
        ("19", PerDiem,                      None),
        ("20", BankCertificate,              None),
        ("21", BankCertificateInterestHistory, None),
        ("22", GoldPrice,                    None),
        ("23", GoldPriceHistory,             None),
        ("24", ExpenseCategory,              "name"),
        ("25", ExpenseSubcategory,           None),
        ("26", Expense,                      None),
        ("27", ReminderRule,                 None),
        ("28", ReminderLog,                  None),
        ("29", Goal,                         None),
        ("30", FixedAsset,                   None),
        ("31", RealEstateDetails,            "asset_id"),
        ("32", AssetMortgage,                "asset_id"),
        ("33", AssetRental,                  "asset_id"),
        ("34", VehicleDetails,               "asset_id"),
        ("35", AssetMaintenance,             None),
        ("36", AssetInsurance,               None),
        ("37", GoldDetails,                  "asset_id"),
        ("38", OtherAssetDetails,            "asset_id"),
        ("39", AssetRenovation,              None),
        ("40", AssetFurniture,               None),
        ("41", AssetValuationHistory,        None),
        ("42", AssetPurchasePayment,         None),
        ("43", AssetSale,                    "asset_id"),
        ("44", Document,                     None),
        ("45", AssetPhoto,                   None),
        ("46", AIConversation,               None),
        ("47", AIMessage,                    None),
        ("48", AIKnowledgeEntry,             "key"),
        ("49", AIModelVersion,               "version_name"),
        ("50", AIBenchmarkReport,            None),
        ("51", CreditCardPayment,            None),
        ("52", BankInterest,                 None),
        ("53", AssetAcquisitionCost,         None),
        ("54", ExchangeRateHistory,          None),
        ("55", Scenario,                     None),
        ("56", ScenarioEvent,                None),
        ("57", AIPromptCategory,             "code"),
        ("58", AIPrompt,                     None),
        ("59", CardRenewalFee,               None),
        ("60", DocumentationExecution,       None),
        ("61", Plan,                         "code"),
        ("62", PlanPrice,                    None),
        ("63", Subscription,                 None),
        ("64", Invoice,                      None),
        ("65", UpgradeRequest,                None),
        ("66", Role,                          "name"),
        ("67", RolePermission,                None),
        ("68", UserRole,                      None),
        ("69", Budget,                        None),
        ("70", RecurringTransaction,          None),
        # login-attempt / lockout records (django-axes) and the admin change history are app data too.
        ("71", AccessAttempt,                 None),
        ("72", AccessAttemptExpiration,       None),
        ("73", AccessFailureLog,              None),
        ("74", AccessLog,                     None),
        ("75", LogEntry,                      None),
        ("76", AIAnswerFeedback,              None),
    ]
