"""
WealthFlow AI Schema & Knowledge Generator.

Automates the generation of system database schema documentation directly from Django model metadata,
preventing documentation drift and keeping the AI system knowledge base updated dynamically.
"""

from __future__ import annotations

import datetime
import inspect
import json
import logging
from pathlib import Path
from typing import Any, Dict, List

from django.apps import apps
from django.conf import settings

logger = logging.getLogger(__name__)


class KnowledgeGenerator:
    """
    Introspects Django models and generates updated database schema documentation.
    """

    @classmethod
    def get_knowledge_dir(cls) -> Path:
        base_dir = getattr(settings, "BASE_DIR", None)
        if base_dir:
            return Path(base_dir) / "ai_knowledge"
        return Path(__file__).resolve().parent.parent.parent.parent / "ai_knowledge"

    @classmethod
    def inspect_models(cls) -> List[Dict[str, Any]]:
        """
        Walks all registered Django models and extracts schema metadata.
        """
        all_models = apps.get_models(include_auto_created=False)
        model_specs = []

        for model in sorted(all_models, key=lambda m: (m._meta.app_label, m.__name__)):
            # Include core app models and auth models
            if model._meta.app_label not in {"core", "auth", "authtoken"}:
                continue

            fields_info = []
            for field in model._meta.get_fields(include_parents=True):
                if field.is_relation and field.many_to_one:
                    rel_to = field.related_model.__name__ if field.related_model else "Unknown"
                    fields_info.append(
                        f"- `{field.name}` ({field.get_internal_type()} -> {rel_to}): FK relation to `{rel_to}`."
                    )
                elif not field.is_relation:
                    ftype = field.get_internal_type() if hasattr(field, "get_internal_type") else type(field).__name__
                    help_txt = getattr(field, "help_text", "") or ""
                    help_suffix = f" — {help_txt}" if help_txt else ""
                    fields_info.append(f"- `{field.name}` ({ftype}){help_suffix}")

            # Inspect calculated @property methods
            props_info = []
            for name, attr in inspect.getmembers(model):
                if isinstance(attr, property) and not name.startswith("_"):
                    doc = inspect.getdoc(attr) or "Calculated property"
                    props_info.append(f"- `{name}` (property): {doc}")

            docstring = (model.__doc__ or "").strip().split("\n")[0]
            model_specs.append({
                "app": model._meta.app_label,
                "name": model.__name__,
                "table": model._meta.db_table,
                "docstring": docstring,
                "fields": fields_info,
                "properties": props_info,
            })

        return model_specs

    @classmethod
    def generate_schema_markdown(cls) -> str:
        """
        Generates clean Markdown content for 02_database_schema.md.
        """
        specs = cls.inspect_models()
        now_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        lines = [
            "# WealthFlow Database Schema & Model Reference",
            "",
            f"> **Auto-Generated Documentation** — Last synchronized: `{now_str}`",
            "> Do not edit this file manually. Run `python manage.py generate_ai_knowledge` to update.",
            "",
            "## Overview",
            "This document provides the authoritative, introspected database schema for WealthFlow Django models.",
            "",
        ]

        current_app = ""
        for spec in specs:
            if spec["app"] != current_app:
                current_app = spec["app"]
                lines.extend([f"## App: `{current_app.upper()}`", ""])

            lines.append(f"### Model: `{spec['name']}` (Table: `{spec['table']}`) ")
            if spec["docstring"]:
                lines.append(f"**Description**: {spec['docstring']}")
            lines.append("")

            lines.append("#### Fields:")
            lines.extend(spec["fields"])
            lines.append("")

            if spec["properties"]:
                lines.append("#### Calculated Properties:")
                lines.extend(spec["properties"])
                lines.append("")

        return "\n".join(lines)

    @classmethod
    def generate_all(cls) -> Dict[str, Any]:
        """
        Regenerates 02_database_schema.md and updates MANIFEST.json metadata.
        """
        knowledge_dir = cls.get_knowledge_dir()
        knowledge_dir.mkdir(parents=True, exist_ok=True)

        # 1. Write updated 02_database_schema.md
        schema_md = cls.generate_schema_markdown()
        schema_path = knowledge_dir / "02_database_schema.md"
        with open(schema_path, "w", encoding="utf-8") as f:
            f.write(schema_md)

        # 2. Update MANIFEST.json metadata
        manifest_path = knowledge_dir / "MANIFEST.json"
        manifest_data: Dict[str, Any] = {}
        if manifest_path.exists():
            try:
                with open(manifest_path, "r", encoding="utf-8") as f:
                    manifest_data = json.load(f)
            except Exception as exc:
                logger.warning("Could not read existing MANIFEST.json during generation: %s", exc)

        now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat()
        manifest_data["manifest_version"] = manifest_data.get("manifest_version", "1.0.0")
        manifest_data["knowledge_version"] = "1.1.0"
        manifest_data["schema_version"] = "2.0.0"
        manifest_data["generated_at"] = now_iso
        manifest_data["application_version"] = getattr(settings, "WEALTHFLOW_VERSION", "1.0.0")

        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest_data, f, indent=2, ensure_ascii=False)

        logger.info("Auto-generated AI database schema knowledge at %s", schema_path)
        return {
            "status": "success",
            "schema_path": str(schema_path),
            "generated_at": now_iso,
            "models_count": len(cls.inspect_models()),
        }
