"""
generate_report_generator package
==================================
NOTE: Split from the former flat core/reports/generate_report_generator.py
(496 lines) per the project's 200-line file-split rule.

Phase-function pattern (see net_worth_service / scenario_planner_service
packages for the same approach): GenerateReportGenerator.post() in core.py
orchestrates a sequence of phase functions, each owning one part of the
PDF, sharing state via the ReportContext dataclass carrier:

- context.py            -- ReportContext dataclass carrier (period info,
                            aggregates, reportlab colors/styles, story list)
- data_phase.py          -- resolve_period, build_report_data: period
                            filtering (monthly/yearly/custom), expense
                            queryset, income/interest/savings aggregates,
                            category totals
- styles.py              -- build_colors, build_styles: reportlab colors
                            and ParagraphStyle objects shared across sections
- section_summary.py     -- append_cover_and_summary: title block + KPI
                            summary table (income/expenses/savings/rate)
- section_categories.py  -- append_category_section: "Expense Breakdown by
                            Category" table
- section_expenses.py    -- append_expense_section: detailed "Expense
                            Entries" table
- section_footer.py      -- append_footer_section: "Generated by
                            WealthFlow" footer line with Arabic month names
- core.py                -- GenerateReportGenerator: request parsing,
                            reportlab document setup, phase orchestration,
                            PDF response

Import from this package exactly as before the split:
    from core.reports.generate_report_generator import GenerateReportGenerator
"""
from core.reports.generate_report_generator.core import GenerateReportGenerator

__all__ = ["GenerateReportGenerator"]
