"""
section_footer.py
==================
NOTE: Part of the generate_report_generator package split (see package
__init__.py docstring). Appends the "Generated by WealthFlow - <date>"
footer line to ctx.story, with Arabic month-name fallback translation.
"""
import datetime

from core.reports.report_utils import format_arabic

ARABIC_MONTHS = {
    "January": "يناير",
    "February": "فبراير",
    "March": "مارس",
    "April": "أبريل",
    "May": "مايو",
    "June": "يونيو",
    "July": "يوليو",
    "August": "أغسطس",
    "September": "سبتمبر",
    "October": "أكتوبر",
    "November": "نوفمبر",
    "December": "ديسمبر",
}


def append_footer_section(ctx):
    from reportlab.lib.units import cm
    from reportlab.platypus import Paragraph, Spacer, HRFlowable

    ctx.story.append(Spacer(1, 1 * cm))
    ctx.story.append(HRFlowable(width="100%", thickness=0.5, color=ctx.colors["grey"]))

    today = datetime.date.today()
    f_day = today.day
    f_year = today.year
    f_month_name = today.strftime("%B")

    f_json_key = f"month_{f_month_name.lower()}"
    f_translated_month = ctx.t.get(f_json_key)

    if not f_translated_month:
        if ctx.lang == "ar":
            f_translated_month = ARABIC_MONTHS.get(f_month_name, f_month_name)
        else:
            f_translated_month = f_month_name

    raw_label = ctx.t.get("generated_by", "Generated by WealthFlow")

    if ctx.lang == "ar":
        raw_footer = f"{raw_label} - {f_day} {f_translated_month} {f_year}"
        footer_text = format_arabic(raw_footer)
    else:
        footer_text = f"{raw_label} - {f_day} {f_translated_month} {f_year}"

    ctx.story.append(Paragraph(footer_text, ctx.styles["footer"]))
