"""GuideRenderMixin: renders a single guide across all supported output
formats (Markdown, HTML, PDF, DOCX), including title translation and
progress-status updates. See this package's __init__.py for the sibling
list and composition conventions."""
import os
import time
from datetime import datetime

from ..config import SUPPORTED_FORMATS


class GuideRenderMixin:
    def _generate_guide(self, guide):
        filtered_nodes = guide.filter_model()
        if not filtered_nodes:
            return
            
        guide_type = guide.get_guide_type()
        guide_dir = self._create_folders(guide_type)
        
        md_path = os.path.join(guide_dir, "markdown", self._get_filename(guide_type, "md"))
        html_path = os.path.join(guide_dir, "html", self._get_filename(guide_type, "html"))
        pdf_path = os.path.join(guide_dir, "pdf", self._get_filename(guide_type, "pdf"))
        docx_path = os.path.join(guide_dir, "docx", self._get_filename(guide_type, "docx"))

        flat_model = self._flatten_tree(filtered_nodes)
        
        # Translate node titles
        for node in flat_model:
            node.title = self._t_title(node.title)
            node.navigation = [self._t_title(x) for x in node.navigation]
            
        context = {
            "app_name": self.manifest.get('application', 'WealthFlow'),
            "guide_type": guide_type.capitalize() + " Guide",
            "title": f"{self.manifest.get('application', 'WealthFlow')} - {guide_type.capitalize()} Guide",
            "date": datetime.now().strftime('%Y-%m-%d'),
            "language": self.metadata.get('language', 'EN').upper() if self.metadata else 'EN',
            "theme": self.metadata.get('theme', 'Dark').capitalize() if self.metadata else 'Dark',
            "device": self.metadata.get('device', 'Desktop').capitalize() if self.metadata else 'Desktop',
            "version": self.manifest.get('version', '1.0'),
            "toc_title": self._t_title("Table of Contents"),
            "nav_title": self._t_title("Navigation Path"),
            "purpose_title": self._t_title("Purpose"),
            "steps_title": self._t_title("Steps"),
            "tech_notes_title": self._t_title("Technical Details"),
            "page_title": self._t_title(guide_type.capitalize() + " Guide"),
            "figure_title": self._t_title("Figure"),
            "lbl_generated": self._t_title("Generated") if self._t_title("Generated") != "Generated" else "تاريخ الإنشاء",
            "lbl_language": self._t_title("Language") if self._t_title("Language") != "Language" else "اللغة",
            "lbl_theme": self._t_title("Theme") if self._t_title("Theme") != "Theme" else "المظهر",
            "lbl_device": self._t_title("Device") if self._t_title("Device") != "Device" else "الجهاز",
            "lbl_version": self._t_title("Version") if self._t_title("Version") != "Version" else "الإصدار",
            "lbl_generated_by": self._t_title("Generated By") if self._t_title("Generated By") != "Generated By" else "تم الإنشاء بواسطة",
            "is_technical": guide.is_technical()
        }
        
        # If language is AR, fallback these labels just in case
        if context["language"] == "AR":
            if context["guide_type"] == "User Guide": context["guide_type"] = "دليل المستخدم"
            if context["guide_type"] == "Admin Guide": context["guide_type"] = "دليل المسؤول"
            if context["guide_type"] == "Technical Guide": context["guide_type"] = "الدليل الفني"
            if context["title"].endswith("User Guide"): context["title"] = "WealthFlow - دليل المستخدم"
            if context["title"].endswith("Admin Guide"): context["title"] = "WealthFlow - دليل المسؤول"
            if context["title"].endswith("Technical Guide"): context["title"] = "WealthFlow - الدليل الفني"

        self._update_status({
            "status": "RUNNING",
            "current_guide": guide_type.capitalize(),
            "current_page": "Markdown",
            "current_output_format": "Markdown",
            "validation_stage": "Generating Markdown",
            "progress_percent": int(((self.current_guide_idx - 1) / self.total_guides) * 100) + 0,
            "elapsed": int(time.time() - self.start_time)
        })
        if "markdown" in SUPPORTED_FORMATS:
            self.renderers["markdown"].render(flat_model, md_path, context)
            
        self._update_status({
            "current_page": "HTML",
            "current_output_format": "HTML",
            "validation_stage": "Generating HTML",
            "progress_percent": int(((self.current_guide_idx - 1) / self.total_guides) * 100) + 6,
            "elapsed": int(time.time() - self.start_time)
        })
        if "html" in SUPPORTED_FORMATS:
            self.renderers["html"].render(md_path, html_path, context)
            
        self._update_status({
            "current_page": "PDF",
            "current_output_format": "PDF",
            "validation_stage": "Generating PDF",
            "progress_percent": int(((self.current_guide_idx - 1) / self.total_guides) * 100) + 12,
            "elapsed": int(time.time() - self.start_time)
        })
        if "pdf" in SUPPORTED_FORMATS:
            self.renderers["pdf"].render(html_path, pdf_path)
            
        self._update_status({
            "current_page": "DOCX",
            "current_output_format": "DOCX",
            "validation_stage": "Generating DOCX",
            "progress_percent": int(((self.current_guide_idx - 1) / self.total_guides) * 100) + 18,
            "elapsed": int(time.time() - self.start_time)
        })
        if "docx" in SUPPORTED_FORMATS:
            self.renderers["docx"].render(flat_model, docx_path, context)

